import setuptools

setuptools.setup(
    name='sprockets.mixins.media_type',
    version='0.0.0',
    description='A mixin for reporting handling content-type/accept headers',
    long_description=open('test-requirements.txt', 'r').read(),
    url='https://github.com/sprockets/sprockets.mixins.media_type',
    author='AWeber Communications',
    author_email='api@aweber.com',
    license='BSD',
    classifiers=[
        'Development Status :: 4 - Beta',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: BSD License',
        'Natural Language :: English',
        'Operating System :: OS Independent',
        'Programming Language :: Python :: 2',
        'Programming Language :: Python :: 2.6',
        'Programming Language :: Python :: 2.7',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.2',
        'Programming Language :: Python :: 3.3',
        'Programming Language :: Python :: 3.4',
        'Programming Language :: Python :: Implementation :: CPython',
        'Programming Language :: Python :: Implementation :: PyPy',
        'Topic :: Software Development :: Libraries',
        'Topic :: Software Development :: Libraries :: Python Modules'
    ],
    packages=['sprockets',
              'sprockets.mixins',
              'sprockets.mixins.media_type'],
    package_data={'': ['LICENSE', 'README.md']},
    include_package_data=True,
    install_requires=['tornado'],
    namespace_packages=['sprockets',
                        'sprockets.mixins'],
    zip_safe=False)
